export const StatusColor = {
  INIT: '#A1D5E5',
  ACCEPTED: '#E5DEA1',
  CANCELED: '#AB9F9F',
  REJECTED_BY_COUNT: '#E5A1A1',
  APPROVED_BY_EXAMINATIONS: '#ABE5A1',
  REJECTED_BY_EXAMINATIONS: '#E5A1A1',
  REJECTED_BY_MISSING_DOCUMENTS: '#E5A1A1',
  MISSING_ON_EXAMINATIONS: '#F2BF72',
  DUPLICATE: '#CCD4DF',
  DOCUMENTS_REQUEST: '#AFA1E5',
  INVITATION_TO_ENTRANCE_EXAMINATION: '#E5A1D2',
  INVITATION_TO_CLASS: '#ABE5A1',
  COMPLETED: '#ADB6C7',
}

export const StatusText = {
  NEW: 'Новая',
  ACCEPTED: 'Принята',
  APPROVED: 'Одобрена',
  DENIED: 'Отклонена',
  DUPLICATED: 'Дубликат',
  DOCUMENTS_REQUEST: 'Запрос документов',
  INVITATION: 'Приглашение на в/и',
}
